# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "RSYNC_SOURCE=/" >> $GITHUB_ENV
          echo "RSYNC_TARGET=/home/ubuntu/gha-sample" >> $GITHUB_ENV

      - name: Deploy by rsync
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete --exclude-from=.rsyncignore
          RSYNC_TARGET: ${{env.RSYNC_TARGET}}
          RSYNC_SOURCE: ${{env.RSYNC_SOURCE}}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SK }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOSTNAME: ${{ secrets.SSH_HOST }}

      - name: run
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SK }}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd gha-sample
            docker-compose stop
            docker-compose up -d --build
